Demo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TotalRevenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TotalRevenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Demo/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity_Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>Unique order Number Order_No</description>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order_No</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>TotalCost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>porder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Demo/src/objects/OrderDetail__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order_No</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderDetails</relationshipLabel>
        <relationshipName>OrderDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>ProductCode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product_Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>OrderDetails</relationshipLabel>
        <relationshipName>OrderDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>OrderDetail</label>
    <nameField>
        <label>OrderDetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demo/src/classes/PlaceOrder.cls
Public class PlaceOrder{
List<productwrapper> productList = new List<productwrapper>();
List<Product2> selectedProducts = new List<Product2>();
public Id Id{get;set;}
public String Discountl ;
  
    
 public List<productwrapper> getProducts()
      {		productList.clear();
          for(Product2 a : [select ProductCode,Name,Description,Discount__c from Product2 limit 5])
          productList.add(new productwrapper(a));
       
          return productList ;
      }
      
          public PageReference getSelected()
      {
        
          selectedProducts.clear();
          for(productwrapper accwrapper : productList)
          if(accwrapper.selected == true)
          selectedProducts.add(accwrapper.acc);
          return null;
      }
       
      public List<Product2> GetSelectedProducts()
      {
          if(selectedProducts.size()>0)
          return selectedProducts;
          else
          return null;
      }   
       
      public class productwrapper
      {
          public Product2 acc{get; set;}
          public Boolean selected {get; set;}
          public productwrapper(Product2 a)
          {
              acc = a;
              selected = false;
          }
      }

 public PageReference createOrder(){
 	if(selectedProducts.size()==0)
 	{
 	  ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Select Atleast One Product From The List');
      ApexPages.addMessage(myMsg); 
       return null;
 	}
    Pattern isnumbers = Pattern.Compile('^[0-9]+$');
    Matcher postalMatch;
    for(Product2 pneww : selectedProducts)
	{
		String ssnew=String.valueOf(pneww.Discount__c);
	 postalMatch = isnumbers.matcher(ssnew);
	
	}
	if(postalMatch.Matches()){
    //has only numbers
    
    	  OrderDetail__c od;
          List<OrderDetail__c> odList;
          Decimal subTotal=0;
          Decimal Amount=0;
          Decimal DAmount=0;
           //String orderid = Apexpages.currentPage().getParameters().get('MyorderId');
           
          //System.debug('oid'+orderid);
          
          Order__c o=[Select ID,Opportunity_Name__c from Order__c order by Order_No__c Desc limit 1];
           List<PriceBookEntry > PricebookList=new List<PriceBookEntry >();
          for(PriceBookEntry at:[Select p.UseStandardPrice, p.UnitPrice, p.SystemModstamp, p.ProductCode, p.Pricebook2Id, p.Name, p.LastModifiedDate, p.LastModifiedById, p.IsDeleted,p.Product2Id, p.IsActive, p.Id From PricebookEntry p  where p.Product2Id IN :selectedProducts  AND PriceBook2.isStandard=true ] )
          {
            
              PricebookList.add(at);
          }
        
         /* for(PriceBookEntry pb:PricebookList)
          {
              System.debug('unitprice'+pb.UnitPrice);
             subTotal=subTotal+pb.UnitPrice;
         }
         system.debug('total'+subTotal);*/
          for(PriceBookEntry pb:PricebookList)
          { 
             // subTotal=pb.UnitPrice+subTotal;
            od=new OrderDetail__c(Order_No__c=o.ID ,Product_Name__c=pb.Product2Id,ProductCode__c=pb.ProductCode,Quantity__c=1,UnitPrice__c=pb.UnitPrice);
              insert od; 
               OrderDetail__c odupdate=[Select Discount__c from OrderDetail__c where Product_Name__c=:pb.Product2Id Limit 1 ];
             for(Product2 p:selectedProducts)
             {
                
                String s=String.valueOf(p.Discount__C);
                Decimal myDecimal = decimal.valueOf(s);
                odupdate.Discount__c=myDecimal;
             }  
             update odupdate;
         }
        
      // o.TotalCost__c=subTotal;
      // update o;
      system.debug('idopp'+o.Opportunity_Name__c);
      Order__c ordernew=[Select ID,TotalCost__c from Order__c order by Order_No__c Desc limit 1];
      
     /*  Opportunity op=[Select ID,TotalRevenue__c from Opportunity  where ID=:o.Opportunity_Name__c limit 1];
        system.debug('opid'+op.TotalRevenue__c);
        String sn=String.valueOf(ordernew.TotalCost__c);
      Decimal myDecimalnew = decimal.valueOf(sn);
      op.TotalRevenue__c=myDecimalnew;
     update op;*/
      
        PageReference reRend1 = new PageReference('https://na15.salesforce.com/a06/o'); 
          return reRend1;
	}
	
    else{
       	ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Enter only Numeric Value');
      ApexPages.addMessage(myMsg); 
       return null;
       }
      }



}